### ISSUE TITLE
Enhancement: Support for TOML Configuration File with -c and --config Flags

### ISSUE THREAD

**Issue by bhavik001** [sshah135/Converter-txtToHtml#9]
Hello,

**Description:**
This enhancement aims to introduce support for TOML configuration files using the -c and --config flags. Users will be able to specify various options in a TOML formatted configuration file, simplifying command line usage and allowing for defaults when necessary. The program should gracefully handle missing or incorrectly formatted files.

Can you please assign me this issue.

**Comment by sshah135** [comment]
HI Bhavik, I have assigned this issue to you
